AppleStore/urls.py
import products
from products.views import createorder
import storefront
from django.contrib import admin
from django.urls import path,include
from storefront import views
from products.views import buyitem
from . import settings
from django.conf.urls.static import static
urlpatterns = [

    #AUTH
    path('admin/', admin.site.urls),
    path('signup/', storefront.views.signupuser, name ='signupuser'),
    path('logout/', storefront.views.logoutuser, name ='logoutuser'),
    path('login/', storefront.views.loginuser, name ='loginuser'),

    #PRODUCTS
    path('products/', include('products.urls')),
    
    #ORDER
    path('createorder/<int:product_id>/', products.views.createorder, name='createorder'),
    path('confirmed/<int:product_id>/', products.views.createorder, name='confirmed'),
    path('allorders', products.views.vieworders, name='vieworders'),
    path('allorders/order/<int:order_id>/', products.views.orderdetails, name='orderdetails'),
    path('allorders/order/cancelorder/<int:order_id>/', products.views.cancelorder, name='cancelorder'),

    #MISC
    path('', storefront.views.home, name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views
import products

app_name = 'products'

urlpatterns = [
    path('',views.buypage, name='products'),
    path('buyitem/', products.views.buypage, name='buypage'),
    path('buyitem/<int:product_id>/',products.views.buyitem, name='buyitem'),



    
]

products/models.py
from django.core.checks.messages import DEBUG
from django.db import models
from django.db.models.deletion import CASCADE, SET_DEFAULT
from django.db.models.enums import Choices
from django.db.models.fields import CharField, DateField, DateTimeField, TextField, URLField
from django.db.models.fields.files import ImageField
from django.contrib.auth.models import User
from django.db.models.fields.related import ForeignKey
from django import forms
from multiselectfield import MultiSelectField 
from django.utils import timezone

class Product(models.Model):
    name = CharField(max_length=100)
    description = TextField(max_length=300)
    image = ImageField(upload_to="products/images", null=True)
    url = URLField(blank=True)
    price = CharField(max_length=5, default='0')

    STORAGE_CHOICES =(
    ("64GB", "64GB"),
    ("128GB", "128GB"),
    ("256GB", "256GB"),
    ("512GB", "512GB"),
    (" "," ")
    )
    storage_options = MultiSelectField(choices = STORAGE_CHOICES, default=STORAGE_CHOICES[0])

    COLOR_CHOICES =(
    ("Red", "Red"),
    ("Blue", "Blue"),
    ("Matte-black", "Matte-black"),
    ("Silver", "Silver"),
    ("","")
    )
    color_options = MultiSelectField(choices = COLOR_CHOICES, default=COLOR_CHOICES[0])
    
    
    def __str__(self):
        return self.name

class Order(models.Model):
    item = models.ForeignKey(Product, on_delete=CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=CASCADE)
    color = models.CharField(max_length=20, default=None)
    storage = models.CharField(max_length=20, default=None)
    order_date = models.DateTimeField(default=None)

    def __str__(self):
        return str(self.item)

storefront/models.py
from django.db import models

# Create your models here.

products/views.py
from django.http.response import HttpResponseNotFound
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.urls.resolvers import get_resolver
from products.models import Product,Order
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render


def buypage(request):
    products = Product.objects.all()
    return render(request, 'buypage.html', {"products":products})

def buyitem(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'buyitem.html', {'product':product})

def createorder(request, product_id):
    
    main_order = get_object_or_404(Product, pk=product_id)
    col_list = []
    for x in main_order.color_options:
        col_list.append(x)

    stor_list = []
    for y in main_order.storage_options:
        stor_list.append(y)

    if request.user.is_authenticated:
        if request.method=='GET':
                return render(request, 'createorder.html', {'order':main_order, 'color_list':col_list, 'storage_list':stor_list})
        else:
            item = get_object_or_404(Product, pk=product_id)
            color = request.POST['color']
            storage = request.POST['storage']
            user = request.user
            date = timezone.now()
            neworder = Order(item=item, color=color, storage=storage, user=user,order_date=date)
            neworder.save()
            return render(request, 'confirmed.html', {'order':neworder, 'main_order':main_order})
        
    else:
        return render(request, 'buyitem.html', {'product':main_order,'error':'PLEASE LOGIN TO BUY'})
                    

def vieworders(request):
    all_orders = Order.objects.filter(user=request.user)
    return render(request, 'vieworders.html', {'allorders':all_orders}) 

def orderdetails(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    return render(request, 'orderdetails.html', {'order':order})
  
def cancelorder(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    if request.method=='POST':
        order.delete()
        return redirect('vieworders')

storefront/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from products.models import Product
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError

# Create your views here.
def home(request):
    products = Product.objects.all()
    return render(request, 'home.html', {"products":products})

def signupuser(request):
    form = UserCreationForm()
    if request.method == "GET":
        return render(request,'signup.html', {'form':form})

    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('home')
            except IntegrityError:
                return render(request, 'signup.html', {'error':'Enter an unique username'})
        else:
            return render(request,'signup.html',{'form':form, 'error':'Password didnt match'})


def loginuser(request):
    form = AuthenticationForm()
    if request.method =='GET':
        return render(request, 'login.html', {'form':form})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'login.html', {'form':form, "error":'No such user found'})
        else:
            login(request, user)
            return redirect('home')
            
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')







    

products/templates/buyitem.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% extends 'base.html' %}
{% block content %}
<div class='main-div'>
{% load static %}

<link rel="stylesheet" href="{% static 'buypage/style.css' %}">

<div class="wrapper text-center"> 
    <h1 class='auth-error'>{{error}}</h1>
    <h1 class="title">{{product.title}}</h4></li>
    <img src="{{ product.image.url}}" height='800'>
    <p class="description">{{product.description|safe}}</p>
    <p class='price'>{{product.price}}</p>

    <button class='order-btn'>
        <a href='{% url 'createorder' product.id %}'>CREATE ORDER</a>
    </button>
</div>
</div>
{% endblock %}

products/templates/confirmed.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'buypage/finish.css' %}">

<div class='wrapper text-center'>
    <label>
        <h1 class='text-1'>YOUR ORDER</h1><br>
            <h1 class='text-0'>
                <a href='{% url 'products:buyitem' main_order.id %}'>
                <label id='name'>{{main_order.name}}
            
                {{order.color}}
                {{order.storage}}</label>
                </a>
            </h1>


        <h1 class='text-2'>
            HAS BEEN PLACED .
        </h1>

        <br>
        <div class='btns'>
            <ul class='btn-list'>
                <li><a href='{% url "home" %}'><button class='btn'>HOME</button></a></li>
                <li><a href='{% url "products:buypage" %}'><button class='btn'>BUY MORE</button></a></li>
                <li><a href='{% url "vieworders" %}'><button class='btn'>MY ORDERS</button></a></li>
            </ul>
        </div>
    </label>
</div>

{% endblock %}

products/templates/createorder.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'buypage/choosepage.css' %}">
<h1>{{error}}</h1>
<h1 class='name text-center'>{{order.title}}</h1><br>
<div class='text-center'>
<img class='image' src="{{ order.image.url}}" height='800'>
</div>

<div class='color-select text-center'>
<form name='orderform' method='POST' action='{% url 'confirmed' order.id %}'>
    {% csrf_token %}
    <div class='color-div'>
    <label class='selector'>
        <h5>select a color :</h3>
    <select class='color-options' name='color'>
        {% for color in color_list %}
            <option value='{{color}}'>
                {{color}}
            </option>
            {% endfor %}
    </select>
    </label>
    </div>
<br>
<div class='storage-div'>
    <label class='selector'>
        <h5>select a storage :</h5>
    <select class='storage-options' name="storage">
        {% for storage in storage_list %}
            <option value={{storage}}>
                {{storage}}
            </option>
            {% endfor %}
    </select>
    </label>
    </div>
    <br>
<button class='confirm-btn' type="submit">CONFIRM</button>
</form>
</div>


{% endblock %}

products/templates/orderdetails.html
{% extends 'base.html' %}

{% block content %}

        



<!DOCTYPE html>
<html>
<head>
{% load static %}
<div class='main-div'>
    {% load static %}
    <link rel="stylesheet" href="{% static 'products/detail.css' %}">
	<title>List item with hover effect</title>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="fontawesome-free/css/all.min.css">
</head>
<body>
	<div class="box">
		<div class="box-header">
			<h1>
				ORDER DETAILS :
            </h1>

		</div>
		<ul class="list">
			<li class="item">
				<i class="left-icon far fa-circle"></i>
				<div>
					Name : {{order.item}}
				</div>
				<i class="right-icon far fa-trash-alt"></i>
			</li>

            {% if order.storage %}
            <li class="item">
				<i class="left-icon far fa-circle"></i>
				<div>
					Storage : {{order.storage}}
				</div>
				<i class="right-icon far fa-trash-alt"></i>
			</li>

            <li class="item">
				<i class="left-icon far fa-circle"></i>
				<div>
					Color : {{order.color}}
				</div>
				<i class="right-icon far fa-trash-alt"></i>
			</li>

            <li class="item">
				<i class="left-icon far fa-circle"></i>
				<div>
					Placed on : {{order.order_date}}
				</div>
				<i class="right-icon far fa-trash-alt"></i>
			</li>
            {% else %}
            <li class="item">
				<i class="left-icon far fa-circle"></i>
				<div>
					Color : {{order.color}}
				</div>
				<i class="right-icon far fa-trash-alt"></i>
			</li>

            <li class="item">
				<i class="left-icon far fa-circle"></i>
				<div>
					Placed on : {{order.order_date}}
				</div>
				<i class="right-icon far fa-trash-alt"></i>
			</li>

		</ul>
	</div>
    {% endif %}
    <div class='cancel-div'>
    <form action='{% url 'cancelorder' order.id %}' method='POST'>
        {% csrf_token %}
        <button class='cancel-btn' type='submit'>CANCEL ORDER</button></a>
    </form>
    </div>
</body>
</div>
</html>
{% endblock %}

products/templates/vieworders.html
{% extends 'base.html' %}

{% block content %}
  
<!DOCTYPE html>
<html>
<head>
{% load static %}
<div class='main-div'>
<link rel="stylesheet" href="{% static 'products/vieworders.css' %}">


	<title>List item with hover effect</title>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
	
	<link rel="stylesheet" type="text/css" href="fontawesome-free/css/all.min.css">
</head>
<body>
	<div class="box">
		<div class="box-header">
			<h1>
				YOUR ORDERS :
            </h1>
        {% if allorders %}
		</div>
		<ul class="list">
            {% for order in allorders %}
			<a class='ordered-item' href='{% url 'orderdetails' order.id%}'>
			<li class="item">
				<i class="left-icon far fa-circle"></i>
				<div class='item-div'>
					{{order.item}}
				</div>
				<i class="right-icon far fa-trash-alt"></i>
			</li>
			</a>
            {% endfor %}
		</ul>
	</div>
    {% else %}
    <div class='error-div'>
    <h1>sorry, you don't have any orders</h1>
    </div>
    <a class='buy-btn' href='{% url "products:buypage" %}'><button class='btn'>BUY</button></a>
        
    {% endif %}
</body>
</div>
</html>
{% endblock %}

storefront/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'base/basestyle.css' %}">
    <title>Apple 2.0</title>
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}"><img class='logo' src="{% static 'base/applelogo.png' %}"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              

              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                 logged in as {{user.username}}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>
                    <form method='POST' action='{% url 'logoutuser' %}'>
                      {% csrf_token %}
                      </a>
                      <div class='btn-div text-center'><button class='logout' type='submit'>LOGOUT</button></div>
                    </form>
                  </li>
                </ul>
              </li>
                {% else %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Join
                  </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'loginuser' %}">Login</a></li>
                  <li><a class="dropdown-item" href="{% url 'signupuser' %}">SignUp</a></li>
                </ul>
              </li>
            
              {% endif %}
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'vieworders' %}">MY ORDERS</a>
              </li>
              {% else %}
              {% endif %}
      </nav>
{% block content %}
{% endblock %}


  </body>
</html>

storefront/templates/buypage.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'products/style.css' %}">
<h1 class="product-heading text-center">BUY PRODUCTS</h1>
<div class="lined-products">
{% for product in products %}
<ul class="list">
    <div class='item-box'>
<li><h4 class="title">{{product.title}}</h4></li>
<a href='#'><img src="{{ product.image.url}}" height='500'></a>
<li><p class="description">{{product.description|safe}}</p></li>
<a href='{% url 'products:buyitem' product.id %}'><button class="buy-btn">BUY</button></a>
    </div>
</ul>
{% endfor %}
{% endblock %}

storefront/templates/home.html
{% extends 'base.html' %}
{% load static %}
<!doctype html>
<head>
    <title>Apple</title>
</head>
<body>
{% block content %}
<link rel="stylesheet" href="{% static 'landpage/homestyle.css' %}">
<img src="{% static 'macbook.jpg' %}" width="2050">
<img src="{% static 'ipad.jpeg' %}" width="2050">
<div class='button text-center'>
    <a href='{% url 'products:products' %}'>
    <button class='buy-btn'>BUY</button>
    </a>
</div>
<h1 class="product-heading text-center">OUR PRODUCTS</h1>
<div class="lined-products">
{% for product in products %}
<ul class="list">
    <div class='item-box'>
<li><h4 class="title">{{product.name}}</h4></li>
<a href='{% url 'products:buyitem' product.id %}'><img class='image-data' src="{{ product.image.url}}" height='600'></a>
<li><p class="description">{{product.description|safe}}</p></li>
    </div>
</ul>
{% endfor %}
{% endblock %}
</div>
</body>
</html>

storefront/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h1>{{error}}</h1>
<form method='POST' action='{% url 'loginuser' %}'>
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit'>LOGIN</button>
</form>
</div>
{% endblock %}

storefront/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>SIGN UP </h1>
<h2>{{error}}</h2>
<form method = 'POST' action='{% url 'signupuser' %}'>
    {% csrf_token %}
    {{form.as_p}}
    <button type='submit'> SIGNUP </button>
</form>
{% endblock %}